<?php

namespace Progmix\Locations\Database\Seeders;

use Illuminate\Database\Seeder;
use DB;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->delete();
        $countries = array(
            array('id' => 1, 'code' => 'AF', 'name' => json_encode(['en' =>  "Afghanistan"]), 'phonecode' => 93),
            array('id' => 2, 'code' => 'AL', 'name' => json_encode(['en' =>  "Albania"]), 'phonecode' => 355),
            array('id' => 3, 'code' => 'DZ', 'name' => json_encode(['en' =>  "Algeria"]), 'phonecode' => 213),
            array('id' => 4, 'code' => 'AS', 'name' => json_encode(['en' =>  "American Samoa"]), 'phonecode' => 1684),
            array('id' => 5, 'code' => 'AD', 'name' => json_encode(['en' =>  "Andorra"]), 'phonecode' => 376),
            array('id' => 6, 'code' => 'AO', 'name' => json_encode(['en' =>  "Angola"]), 'phonecode' => 244),
            array('id' => 7, 'code' => 'AI', 'name' => json_encode(['en' =>  "Anguilla"]), 'phonecode' => 1264),
            array('id' => 8, 'code' => 'AQ', 'name' => json_encode(['en' =>  "Antarctica"]), 'phonecode' => 0),
            array('id' => 9, 'code' => 'AG', 'name' => json_encode(['en' =>  "Antigua And Barbuda"]), 'phonecode' => 1268),
            array('id' => 10, 'code' => 'AR', 'name' => json_encode(['en' =>  "Argentina"]), 'phonecode' => 54),
            array('id' => 11, 'code' => 'AM', 'name' => json_encode(['en' =>  "Armenia"]), 'phonecode' => 374),
            array('id' => 12, 'code' => 'AW', 'name' => json_encode(['en' =>  "Aruba"]), 'phonecode' => 297),
            array('id' => 13, 'code' => 'AU', 'name' => json_encode(['en' =>  "Australia"]), 'phonecode' => 61),
            array('id' => 14, 'code' => 'AT', 'name' => json_encode(['en' =>  "Austria"]), 'phonecode' => 43),
            array('id' => 15, 'code' => 'AZ', 'name' => json_encode(['en' =>  "Azerbaijan"]), 'phonecode' => 994),
            array('id' => 16, 'code' => 'BS', 'name' => json_encode(['en' =>  "Bahamas The"]), 'phonecode' => 1242),
            array('id' => 17, 'code' => 'BH', 'name' => json_encode(['en' =>  "Bahrain"]), 'phonecode' => 973),
            array('id' => 18, 'code' => 'BD', 'name' => json_encode(['en' =>  "Bangladesh"]), 'phonecode' => 880),
            array('id' => 19, 'code' => 'BB', 'name' => json_encode(['en' =>  "Barbados"]), 'phonecode' => 1246),
            array('id' => 20, 'code' => 'BY', 'name' => json_encode(['en' =>  "Belarus"]), 'phonecode' => 375),
            array('id' => 21, 'code' => 'BE', 'name' => json_encode(['en' =>  "Belgium"]), 'phonecode' => 32),
            array('id' => 22, 'code' => 'BZ', 'name' => json_encode(['en' =>  "Belize"]), 'phonecode' => 501),
            array('id' => 23, 'code' => 'BJ', 'name' => json_encode(['en' =>  "Benin"]), 'phonecode' => 229),
            array('id' => 24, 'code' => 'BM', 'name' => json_encode(['en' =>  "Bermuda"]), 'phonecode' => 1441),
            array('id' => 25, 'code' => 'BT', 'name' => json_encode(['en' =>  "Bhutan"]), 'phonecode' => 975),
            array('id' => 26, 'code' => 'BO', 'name' => json_encode(['en' =>  "Bolivia"]), 'phonecode' => 591),
            array('id' => 27, 'code' => 'BA', 'name' => json_encode(['en' =>  "Bosnia and Herzegovina"]), 'phonecode' => 387),
            array('id' => 28, 'code' => 'BW', 'name' => json_encode(['en' =>  "Botswana"]), 'phonecode' => 267),
            array('id' => 29, 'code' => 'BV', 'name' => json_encode(['en' =>  "Bouvet Island"]), 'phonecode' => 0),
            array('id' => 30, 'code' => 'BR', 'name' => json_encode(['en' =>  "Brazil"]), 'phonecode' => 55),
            array('id' => 31, 'code' => 'IO', 'name' => json_encode(['en' =>  "British Indian Ocean Territory"]), 'phonecode' => 246),
            array('id' => 32, 'code' => 'BN', 'name' => json_encode(['en' =>  "Brunei"]), 'phonecode' => 673),
            array('id' => 33, 'code' => 'BG', 'name' => json_encode(['en' =>  "Bulgaria"]), 'phonecode' => 359),
            array('id' => 34, 'code' => 'BF', 'name' => json_encode(['en' =>  "Burkina Faso"]), 'phonecode' => 226),
            array('id' => 35, 'code' => 'BI', 'name' => json_encode(['en' =>  "Burundi"]), 'phonecode' => 257),
            array('id' => 36, 'code' => 'KH', 'name' => json_encode(['en' =>  "Cambodia"]), 'phonecode' => 855),
            array('id' => 37, 'code' => 'CM', 'name' => json_encode(['en' =>  "Cameroon"]), 'phonecode' => 237),
            array('id' => 38, 'code' => 'CA', 'name' => json_encode(['en' =>  "Canada"]), 'phonecode' => 1),
            array('id' => 39, 'code' => 'CV', 'name' => json_encode(['en' =>  "Cape Verde"]), 'phonecode' => 238),
            array('id' => 40, 'code' => 'KY', 'name' => json_encode(['en' =>  "Cayman Islands"]), 'phonecode' => 1345),
            array('id' => 41, 'code' => 'CF', 'name' => json_encode(['en' =>  "Central African Republic"]), 'phonecode' => 236),
            array('id' => 42, 'code' => 'TD', 'name' => json_encode(['en' =>  "Chad"]), 'phonecode' => 235),
            array('id' => 43, 'code' => 'CL', 'name' => json_encode(['en' =>  "Chile"]), 'phonecode' => 56),
            array('id' => 44, 'code' => 'CN', 'name' => json_encode(['en' =>  "China"]), 'phonecode' => 86),
            array('id' => 45, 'code' => 'CX', 'name' => json_encode(['en' =>  "Christmas Island"]), 'phonecode' => 61),
            array('id' => 46, 'code' => 'CC', 'name' => json_encode(['en' =>  "Cocos (Keeling) Islands"]), 'phonecode' => 672),
            array('id' => 47, 'code' => 'CO', 'name' => json_encode(['en' =>  "Colombia"]), 'phonecode' => 57),
            array('id' => 48, 'code' => 'KM', 'name' => json_encode(['en' =>  "Comoros"]), 'phonecode' => 269),
            array('id' => 49, 'code' => 'CG', 'name' => json_encode(['en' =>  "Congo"]), 'phonecode' => 242),
            array('id' => 50, 'code' => 'CD', 'name' => json_encode(['en' =>  "Congo The Democratic Republic Of The"]), 'phonecode' => 242),
            array('id' => 51, 'code' => 'CK', 'name' => json_encode(['en' =>  "Cook Islands"]), 'phonecode' => 682),
            array('id' => 52, 'code' => 'CR', 'name' => json_encode(['en' =>  "Costa Rica"]), 'phonecode' => 506),
            array('id' => 53, 'code' => 'CI', 'name' => json_encode(['en' =>  "Cote D Ivoire (Ivory Coast)"]), 'phonecode' => 225),
            array('id' => 54, 'code' => 'HR', 'name' => json_encode(['en' =>  "Croatia (Hrvatska)"]), 'phonecode' => 385),
            array('id' => 55, 'code' => 'CU', 'name' => json_encode(['en' =>  "Cuba"]), 'phonecode' => 53),
            array('id' => 56, 'code' => 'CY', 'name' => json_encode(['en' =>  "Cyprus"]), 'phonecode' => 357),
            array('id' => 57, 'code' => 'CZ', 'name' => json_encode(['en' =>  "Czech Republic"]), 'phonecode' => 420),
            array('id' => 58, 'code' => 'DK', 'name' => json_encode(['en' =>  "Denmark"]), 'phonecode' => 45),
            array('id' => 59, 'code' => 'DJ', 'name' => json_encode(['en' =>  "Djibouti"]), 'phonecode' => 253),
            array('id' => 60, 'code' => 'DM', 'name' => json_encode(['en' =>  "Dominica"]), 'phonecode' => 1767),
            array('id' => 61, 'code' => 'DO', 'name' => json_encode(['en' =>  "Dominican Republic"]), 'phonecode' => 1809),
            array('id' => 62, 'code' => 'TP', 'name' => json_encode(['en' =>  "East Timor"]), 'phonecode' => 670),
            array('id' => 63, 'code' => 'EC', 'name' => json_encode(['en' =>  "Ecuador"]), 'phonecode' => 593),
            array('id' => 64, 'code' => 'EG', 'name' => json_encode(['en' =>  "Egypt"]), 'phonecode' => 20),
            array('id' => 65, 'code' => 'SV', 'name' => json_encode(['en' =>  "El Salvador"]), 'phonecode' => 503),
            array('id' => 66, 'code' => 'GQ', 'name' => json_encode(['en' =>  "Equatorial Guinea"]), 'phonecode' => 240),
            array('id' => 67, 'code' => 'ER', 'name' => json_encode(['en' =>  "Eritrea"]), 'phonecode' => 291),
            array('id' => 68, 'code' => 'EE', 'name' => json_encode(['en' =>  "Estonia"]), 'phonecode' => 372),
            array('id' => 69, 'code' => 'ET', 'name' => json_encode(['en' =>  "Ethiopia"]), 'phonecode' => 251),
            array('id' => 70, 'code' => 'XA', 'name' => json_encode(['en' =>  "External Territories of Australia"]), 'phonecode' => 61),
            array('id' => 71, 'code' => 'FK', 'name' => json_encode(['en' =>  "Falkland Islands"]), 'phonecode' => 500),
            array('id' => 72, 'code' => 'FO', 'name' => json_encode(['en' =>  "Faroe Islands"]), 'phonecode' => 298),
            array('id' => 73, 'code' => 'FJ', 'name' => json_encode(['en' =>  "Fiji Islands"]), 'phonecode' => 679),
            array('id' => 74, 'code' => 'FI', 'name' => json_encode(['en' =>  "Finland"]), 'phonecode' => 358),
            array('id' => 75, 'code' => 'FR', 'name' => json_encode(['en' =>  "France"]), 'phonecode' => 33),
            array('id' => 76, 'code' => 'GF', 'name' => json_encode(['en' =>  "French Guiana"]), 'phonecode' => 594),
            array('id' => 77, 'code' => 'PF', 'name' => json_encode(['en' =>  "French Polynesia"]), 'phonecode' => 689),
            array('id' => 78, 'code' => 'TF', 'name' => json_encode(['en' =>  "French Southern Territories"]), 'phonecode' => 0),
            array('id' => 79, 'code' => 'GA', 'name' => json_encode(['en' =>  "Gabon"]), 'phonecode' => 241),
            array('id' => 80, 'code' => 'GM', 'name' => json_encode(['en' =>  "Gambia The"]), 'phonecode' => 220),
            array('id' => 81, 'code' => 'GE', 'name' => json_encode(['en' =>  "Georgia"]), 'phonecode' => 995),
            array('id' => 82, 'code' => 'DE', 'name' => json_encode(['en' =>  "Germany"]), 'phonecode' => 49),
            array('id' => 83, 'code' => 'GH', 'name' => json_encode(['en' =>  "Ghana"]), 'phonecode' => 233),
            array('id' => 84, 'code' => 'GI', 'name' => json_encode(['en' =>  "Gibraltar"]), 'phonecode' => 350),
            array('id' => 85, 'code' => 'GR', 'name' => json_encode(['en' =>  "Greece"]), 'phonecode' => 30),
            array('id' => 86, 'code' => 'GL', 'name' => json_encode(['en' =>  "Greenland"]), 'phonecode' => 299),
            array('id' => 87, 'code' => 'GD', 'name' => json_encode(['en' =>  "Grenada"]), 'phonecode' => 1473),
            array('id' => 88, 'code' => 'GP', 'name' => json_encode(['en' =>  "Guadeloupe"]), 'phonecode' => 590),
            array('id' => 89, 'code' => 'GU', 'name' => json_encode(['en' =>  "Guam"]), 'phonecode' => 1671),
            array('id' => 90, 'code' => 'GT', 'name' => json_encode(['en' =>  "Guatemala"]), 'phonecode' => 502),
            array('id' => 91, 'code' => 'XU', 'name' => json_encode(['en' =>  "Guernsey and Alderney"]), 'phonecode' => 44),
            array('id' => 92, 'code' => 'GN', 'name' => json_encode(['en' =>  "Guinea"]), 'phonecode' => 224),
            array('id' => 93, 'code' => 'GW', 'name' => json_encode(['en' =>  "Guinea-Bissau"]), 'phonecode' => 245),
            array('id' => 94, 'code' => 'GY', 'name' => json_encode(['en' =>  "Guyana"]), 'phonecode' => 592),
            array('id' => 95, 'code' => 'HT', 'name' => json_encode(['en' =>  "Haiti"]), 'phonecode' => 509),
            array('id' => 96, 'code' => 'HM', 'name' => json_encode(['en' =>  "Heard and McDonald Islands"]), 'phonecode' => 0),
            array('id' => 97, 'code' => 'HN', 'name' => json_encode(['en' =>  "Honduras"]), 'phonecode' => 504),
            array('id' => 98, 'code' => 'HK', 'name' => json_encode(['en' =>  "Hong Kong S.A.R."]), 'phonecode' => 852),
            array('id' => 99, 'code' => 'HU', 'name' => json_encode(['en' =>  "Hungary"]), 'phonecode' => 36),
            array('id' => 100, 'code' => 'IS', 'name' => json_encode(['en' =>  "Iceland"]), 'phonecode' => 354),
            array('id' => 101, 'code' => 'IN', 'name' => json_encode(['en' =>  "India"]), 'phonecode' => 91),
            array('id' => 102, 'code' => 'ID', 'name' => json_encode(['en' =>  "Indonesia"]), 'phonecode' => 62),
            array('id' => 103, 'code' => 'IR', 'name' => json_encode(['en' =>  "Iran"]), 'phonecode' => 98),
            array('id' => 104, 'code' => 'IQ', 'name' => json_encode(['en' =>  "Iraq"]), 'phonecode' => 964),
            array('id' => 105, 'code' => 'IE', 'name' => json_encode(['en' =>  "Ireland"]), 'phonecode' => 353),
            array('id' => 106, 'code' => 'IL', 'name' => json_encode(['en' =>  "Israel"]), 'phonecode' => 972),
            array('id' => 107, 'code' => 'IT', 'name' => json_encode(['en' =>  "Italy"]), 'phonecode' => 39),
            array('id' => 108, 'code' => 'JM', 'name' => json_encode(['en' =>  "Jamaica"]), 'phonecode' => 1876),
            array('id' => 109, 'code' => 'JP', 'name' => json_encode(['en' =>  "Japan"]), 'phonecode' => 81),
            array('id' => 110, 'code' => 'XJ', 'name' => json_encode(['en' =>  "Jersey"]), 'phonecode' => 44),
            array('id' => 111, 'code' => 'JO', 'name' => json_encode(['en' =>  "Jordan"]), 'phonecode' => 962),
            array('id' => 112, 'code' => 'KZ', 'name' => json_encode(['en' =>  "Kazakhstan"]), 'phonecode' => 7),
            array('id' => 113, 'code' => 'KE', 'name' => json_encode(['en' =>  "Kenya"]), 'phonecode' => 254),
            array('id' => 114, 'code' => 'KI', 'name' => json_encode(['en' =>  "Kiribati"]), 'phonecode' => 686),
            array('id' => 115, 'code' => 'KP', 'name' => json_encode(['en' =>  "Korea North"]), 'phonecode' => 850),
            array('id' => 116, 'code' => 'KR', 'name' => json_encode(['en' =>  "Korea South"]), 'phonecode' => 82),
            array('id' => 117, 'code' => 'KW', 'name' => json_encode(['en' =>  "Kuwait"]), 'phonecode' => 965),
            array('id' => 118, 'code' => 'KG', 'name' => json_encode(['en' =>  "Kyrgyzstan"]), 'phonecode' => 996),
            array('id' => 119, 'code' => 'LA', 'name' => json_encode(['en' =>  "Laos"]), 'phonecode' => 856),
            array('id' => 120, 'code' => 'LV', 'name' => json_encode(['en' =>  "Latvia"]), 'phonecode' => 371),
            array('id' => 121, 'code' => 'LB', 'name' => json_encode(['en' =>  "Lebanon"]), 'phonecode' => 961),
            array('id' => 122, 'code' => 'LS', 'name' => json_encode(['en' =>  "Lesotho"]), 'phonecode' => 266),
            array('id' => 123, 'code' => 'LR', 'name' => json_encode(['en' =>  "Liberia"]), 'phonecode' => 231),
            array('id' => 124, 'code' => 'LY', 'name' => json_encode(['en' =>  "Libya"]), 'phonecode' => 218),
            array('id' => 125, 'code' => 'LI', 'name' => json_encode(['en' =>  "Liechtenstein"]), 'phonecode' => 423),
            array('id' => 126, 'code' => 'LT', 'name' => json_encode(['en' =>  "Lithuania"]), 'phonecode' => 370),
            array('id' => 127, 'code' => 'LU', 'name' => json_encode(['en' =>  "Luxembourg"]), 'phonecode' => 352),
            array('id' => 128, 'code' => 'MO', 'name' => json_encode(['en' =>  "Macau S.A.R."]), 'phonecode' => 853),
            array('id' => 129, 'code' => 'MK', 'name' => json_encode(['en' =>  "Macedonia"]), 'phonecode' => 389),
            array('id' => 130, 'code' => 'MG', 'name' => json_encode(['en' =>  "Madagascar"]), 'phonecode' => 261),
            array('id' => 131, 'code' => 'MW', 'name' => json_encode(['en' =>  "Malawi"]), 'phonecode' => 265),
            array('id' => 132, 'code' => 'MY', 'name' => json_encode(['en' =>  "Malaysia"]), 'phonecode' => 60),
            array('id' => 133, 'code' => 'MV', 'name' => json_encode(['en' =>  "Maldives"]), 'phonecode' => 960),
            array('id' => 134, 'code' => 'ML', 'name' => json_encode(['en' =>  "Mali"]), 'phonecode' => 223),
            array('id' => 135, 'code' => 'MT', 'name' => json_encode(['en' =>  "Malta"]), 'phonecode' => 356),
            array('id' => 136, 'code' => 'XM', 'name' => json_encode(['en' =>  "Man (Isle of)"]), 'phonecode' => 44),
            array('id' => 137, 'code' => 'MH', 'name' => json_encode(['en' =>  "Marshall Islands"]), 'phonecode' => 692),
            array('id' => 138, 'code' => 'MQ', 'name' => json_encode(['en' =>  "Martinique"]), 'phonecode' => 596),
            array('id' => 139, 'code' => 'MR', 'name' => json_encode(['en' =>  "Mauritania"]), 'phonecode' => 222),
            array('id' => 140, 'code' => 'MU', 'name' => json_encode(['en' =>  "Mauritius"]), 'phonecode' => 230),
            array('id' => 141, 'code' => 'YT', 'name' => json_encode(['en' =>  "Mayotte"]), 'phonecode' => 269),
            array('id' => 142, 'code' => 'MX', 'name' => json_encode(['en' =>  "Mexico"]), 'phonecode' => 52),
            array('id' => 143, 'code' => 'FM', 'name' => json_encode(['en' =>  "Micronesia"]), 'phonecode' => 691),
            array('id' => 144, 'code' => 'MD', 'name' => json_encode(['en' =>  "Moldova"]), 'phonecode' => 373),
            array('id' => 145, 'code' => 'MC', 'name' => json_encode(['en' =>  "Monaco"]), 'phonecode' => 377),
            array('id' => 146, 'code' => 'MN', 'name' => json_encode(['en' =>  "Mongolia"]), 'phonecode' => 976),
            array('id' => 147, 'code' => 'MS', 'name' => json_encode(['en' =>  "Montserrat"]), 'phonecode' => 1664),
            array('id' => 148, 'code' => 'MA', 'name' => json_encode(['en' =>  "Morocco"]), 'phonecode' => 212),
            array('id' => 149, 'code' => 'MZ', 'name' => json_encode(['en' =>  "Mozambique"]), 'phonecode' => 258),
            array('id' => 150, 'code' => 'MM', 'name' => json_encode(['en' =>  "Myanmar"]), 'phonecode' => 95),
            array('id' => 151, 'code' => 'NA', 'name' => json_encode(['en' =>  "Namibia"]), 'phonecode' => 264),
            array('id' => 152, 'code' => 'NR', 'name' => json_encode(['en' =>  "Nauru"]), 'phonecode' => 674),
            array('id' => 153, 'code' => 'NP', 'name' => json_encode(['en' =>  "Nepal"]), 'phonecode' => 977),
            array('id' => 154, 'code' => 'AN', 'name' => json_encode(['en' =>  "Netherlands Antilles"]), 'phonecode' => 599),
            array('id' => 155, 'code' => 'NL', 'name' => json_encode(['en' =>  "Netherlands The"]), 'phonecode' => 31),
            array('id' => 156, 'code' => 'NC', 'name' => json_encode(['en' =>  "New Caledonia"]), 'phonecode' => 687),
            array('id' => 157, 'code' => 'NZ', 'name' => json_encode(['en' =>  "New Zealand"]), 'phonecode' => 64),
            array('id' => 158, 'code' => 'NI', 'name' => json_encode(['en' =>  "Nicaragua"]), 'phonecode' => 505),
            array('id' => 159, 'code' => 'NE', 'name' => json_encode(['en' =>  "Niger"]), 'phonecode' => 227),
            array('id' => 160, 'code' => 'NG', 'name' => json_encode(['en' =>  "Nigeria"]), 'phonecode' => 234),
            array('id' => 161, 'code' => 'NU', 'name' => json_encode(['en' =>  "Niue"]), 'phonecode' => 683),
            array('id' => 162, 'code' => 'NF', 'name' => json_encode(['en' =>  "Norfolk Island"]), 'phonecode' => 672),
            array('id' => 163, 'code' => 'MP', 'name' => json_encode(['en' =>  "Northern Mariana Islands"]), 'phonecode' => 1670),
            array('id' => 164, 'code' => 'NO', 'name' => json_encode(['en' =>  "Norway"]), 'phonecode' => 47),
            array('id' => 165, 'code' => 'OM', 'name' => json_encode(['en' =>  "Oman"]), 'phonecode' => 968),
            array('id' => 166, 'code' => 'PK', 'name' => json_encode(['en' =>  "Pakistan"]), 'phonecode' => 92),
            array('id' => 167, 'code' => 'PW', 'name' => json_encode(['en' =>  "Palau"]), 'phonecode' => 680),
            array('id' => 168, 'code' => 'PS', 'name' => json_encode(['en' =>  "Palestinian Territory Occupied"]), 'phonecode' => 970),
            array('id' => 169, 'code' => 'PA', 'name' => json_encode(['en' =>  "Panama"]), 'phonecode' => 507),
            array('id' => 170, 'code' => 'PG', 'name' => json_encode(['en' =>  "Papua new Guinea"]), 'phonecode' => 675),
            array('id' => 171, 'code' => 'PY', 'name' => json_encode(['en' =>  "Paraguay"]), 'phonecode' => 595),
            array('id' => 172, 'code' => 'PE', 'name' => json_encode(['en' =>  "Peru"]), 'phonecode' => 51),
            array('id' => 173, 'code' => 'PH', 'name' => json_encode(['en' =>  "Philippines"]), 'phonecode' => 63),
            array('id' => 174, 'code' => 'PN', 'name' => json_encode(['en' =>  "Pitcairn Island"]), 'phonecode' => 0),
            array('id' => 175, 'code' => 'PL', 'name' => json_encode(['en' =>  "Poland"]), 'phonecode' => 48),
            array('id' => 176, 'code' => 'PT', 'name' => json_encode(['en' =>  "Portugal"]), 'phonecode' => 351),
            array('id' => 177, 'code' => 'PR', 'name' => json_encode(['en' =>  "Puerto Rico"]), 'phonecode' => 1787),
            array('id' => 178, 'code' => 'QA', 'name' => json_encode(['en' =>  "Qatar"]), 'phonecode' => 974),
            array('id' => 179, 'code' => 'RE', 'name' => json_encode(['en' =>  "Reunion"]), 'phonecode' => 262),
            array('id' => 180, 'code' => 'RO', 'name' => json_encode(['en' =>  "Romania"]), 'phonecode' => 40),
            array('id' => 181, 'code' => 'RU', 'name' => json_encode(['en' =>  "Russia"]), 'phonecode' => 70),
            array('id' => 182, 'code' => 'RW', 'name' => json_encode(['en' =>  "Rwanda"]), 'phonecode' => 250),
            array('id' => 183, 'code' => 'SH', 'name' => json_encode(['en' =>  "Saint Helena"]), 'phonecode' => 290),
            array('id' => 184, 'code' => 'KN', 'name' => json_encode(['en' =>  "Saint Kitts And Nevis"]), 'phonecode' => 1869),
            array('id' => 185, 'code' => 'LC', 'name' => json_encode(['en' =>  "Saint Lucia"]), 'phonecode' => 1758),
            array('id' => 186, 'code' => 'PM', 'name' => json_encode(['en' =>  "Saint Pierre and Miquelon"]), 'phonecode' => 508),
            array('id' => 187, 'code' => 'VC', 'name' => json_encode(['en' =>  "Saint Vincent And The Grenadines"]), 'phonecode' => 1784),
            array('id' => 188, 'code' => 'WS', 'name' => json_encode(['en' =>  "Samoa"]), 'phonecode' => 684),
            array('id' => 189, 'code' => 'SM', 'name' => json_encode(['en' =>  "San Marino"]), 'phonecode' => 378),
            array('id' => 190, 'code' => 'ST', 'name' => json_encode(['en' =>  "Sao Tome and Principe"]), 'phonecode' => 239),
            array('id' => 191, 'code' => 'SA', 'name' => json_encode(['en' =>  "Saudi Arabia"]), 'phonecode' => 966),
            array('id' => 192, 'code' => 'SN', 'name' => json_encode(['en' =>  "Senegal"]), 'phonecode' => 221),
            array('id' => 193, 'code' => 'RS', 'name' => json_encode(['en' =>  "Serbia"]), 'phonecode' => 381),
            array('id' => 194, 'code' => 'SC', 'name' => json_encode(['en' =>  "Seychelles"]), 'phonecode' => 248),
            array('id' => 195, 'code' => 'SL', 'name' => json_encode(['en' =>  "Sierra Leone"]), 'phonecode' => 232),
            array('id' => 196, 'code' => 'SG', 'name' => json_encode(['en' =>  "Singapore"]), 'phonecode' => 65),
            array('id' => 197, 'code' => 'SK', 'name' => json_encode(['en' =>  "Slovakia"]), 'phonecode' => 421),
            array('id' => 198, 'code' => 'SI', 'name' => json_encode(['en' =>  "Slovenia"]), 'phonecode' => 386),
            array('id' => 199, 'code' => 'XG', 'name' => json_encode(['en' =>  "Smaller Territories of the UK"]), 'phonecode' => 44),
            array('id' => 200, 'code' => 'SB', 'name' => json_encode(['en' =>  "Solomon Islands"]), 'phonecode' => 677),
            array('id' => 201, 'code' => 'SO', 'name' => json_encode(['en' =>  "Somalia"]), 'phonecode' => 252),
            array('id' => 202, 'code' => 'ZA', 'name' => json_encode(['en' =>  "South Africa"]), 'phonecode' => 27),
            array('id' => 203, 'code' => 'GS', 'name' => json_encode(['en' =>  "South Georgia"]), 'phonecode' => 0),
            array('id' => 204, 'code' => 'SS', 'name' => json_encode(['en' =>  "South Sudan"]), 'phonecode' => 211),
            array('id' => 205, 'code' => 'ES', 'name' => json_encode(['en' =>  "Spain"]), 'phonecode' => 34),
            array('id' => 206, 'code' => 'LK', 'name' => json_encode(['en' =>  "Sri Lanka"]), 'phonecode' => 94),
            array('id' => 207, 'code' => 'SD', 'name' => json_encode(['en' =>  "Sudan"]), 'phonecode' => 249),
            array('id' => 208, 'code' => 'SR', 'name' => json_encode(['en' =>  "Suriname"]), 'phonecode' => 597),
            array('id' => 209, 'code' => 'SJ', 'name' => json_encode(['en' =>  "Svalbard And Jan Mayen Islands"]), 'phonecode' => 47),
            array('id' => 210, 'code' => 'SZ', 'name' => json_encode(['en' =>  "Swaziland"]), 'phonecode' => 268),
            array('id' => 211, 'code' => 'SE', 'name' => json_encode(['en' =>  "Sweden"]), 'phonecode' => 46),
            array('id' => 212, 'code' => 'CH', 'name' => json_encode(['en' =>  "Switzerland"]), 'phonecode' => 41),
            array('id' => 213, 'code' => 'SY', 'name' => json_encode(['en' =>  "Syria"]), 'phonecode' => 963),
            array('id' => 214, 'code' => 'TW', 'name' => json_encode(['en' =>  "Taiwan"]), 'phonecode' => 886),
            array('id' => 215, 'code' => 'TJ', 'name' => json_encode(['en' =>  "Tajikistan"]), 'phonecode' => 992),
            array('id' => 216, 'code' => 'TZ', 'name' => json_encode(['en' =>  "Tanzania"]), 'phonecode' => 255),
            array('id' => 217, 'code' => 'TH', 'name' => json_encode(['en' =>  "Thailand"]), 'phonecode' => 66),
            array('id' => 218, 'code' => 'TG', 'name' => json_encode(['en' =>  "Togo"]), 'phonecode' => 228),
            array('id' => 219, 'code' => 'TK', 'name' => json_encode(['en' =>  "Tokelau"]), 'phonecode' => 690),
            array('id' => 220, 'code' => 'TO', 'name' => json_encode(['en' =>  "Tonga"]), 'phonecode' => 676),
            array('id' => 221, 'code' => 'TT', 'name' => json_encode(['en' =>  "Trinidad And Tobago"]), 'phonecode' => 1868),
            array('id' => 222, 'code' => 'TN', 'name' => json_encode(['en' =>  "Tunisia"]), 'phonecode' => 216),
            array('id' => 223, 'code' => 'TR', 'name' => json_encode(['en' =>  "Turkey"]), 'phonecode' => 90),
            array('id' => 224, 'code' => 'TM', 'name' => json_encode(['en' =>  "Turkmenistan"]), 'phonecode' => 7370),
            array('id' => 225, 'code' => 'TC', 'name' => json_encode(['en' =>  "Turks And Caicos Islands"]), 'phonecode' => 1649),
            array('id' => 226, 'code' => 'TV', 'name' => json_encode(['en' =>  "Tuvalu"]), 'phonecode' => 688),
            array('id' => 227, 'code' => 'UG', 'name' => json_encode(['en' =>  "Uganda"]), 'phonecode' => 256),
            array('id' => 228, 'code' => 'UA', 'name' => json_encode(['en' =>  "Ukraine"]), 'phonecode' => 380),
            array('id' => 229, 'code' => 'AE', 'name' => json_encode(['en' =>  "United Arab Emirates"]), 'phonecode' => 971),
            array('id' => 230, 'code' => 'GB', 'name' => json_encode(['en' =>  "United Kingdom"]), 'phonecode' => 44),
            array('id' => 231, 'code' => 'US', 'name' => json_encode(['en' =>  "United States"]), 'phonecode' => 1),
            array('id' => 232, 'code' => 'UM', 'name' => json_encode(['en' =>  "United States Minor Outlying Islands"]), 'phonecode' => 1),
            array('id' => 233, 'code' => 'UY', 'name' => json_encode(['en' =>  "Uruguay"]), 'phonecode' => 598),
            array('id' => 234, 'code' => 'UZ', 'name' => json_encode(['en' =>  "Uzbekistan"]), 'phonecode' => 998),
            array('id' => 235, 'code' => 'VU', 'name' => json_encode(['en' =>  "Vanuatu"]), 'phonecode' => 678),
            array('id' => 236, 'code' => 'VA', 'name' => json_encode(['en' =>  "Vatican City State (Holy See)"]), 'phonecode' => 39),
            array('id' => 237, 'code' => 'VE', 'name' => json_encode(['en' =>  "Venezuela"]), 'phonecode' => 58),
            array('id' => 238, 'code' => 'VN', 'name' => json_encode(['en' =>  "Vietnam"]), 'phonecode' => 84),
            array('id' => 239, 'code' => 'VG', 'name' => json_encode(['en' =>  "Virgin Islands (British)"]), 'phonecode' => 1284),
            array('id' => 240, 'code' => 'VI', 'name' => json_encode(['en' =>  "Virgin Islands (US)"]), 'phonecode' => 1340),
            array('id' => 241, 'code' => 'WF', 'name' => json_encode(['en' =>  "Wallis And Futuna Islands"]), 'phonecode' => 681),
            array('id' => 242, 'code' => 'EH', 'name' => json_encode(['en' =>  "Western Sahara"]), 'phonecode' => 212),
            array('id' => 243, 'code' => 'YE', 'name' => json_encode(['en' =>  "Yemen"]), 'phonecode' => 967),
            array('id' => 244, 'code' => 'YU', 'name' => json_encode(['en' =>  "Yugoslavia"]), 'phonecode' => 38),
            array('id' => 245, 'code' => 'ZM', 'name' => json_encode(['en' =>  "Zambia"]), 'phonecode' => 260),
            array('id' => 246, 'code' => 'ZW', 'name' => json_encode(['en' =>  "Zimbabwe"]), 'phonecode' => 263),
        );
        DB::table('countries')->insert($countries);
    }
}
